### ISSUE TITLE
请问，我运行之后好像编辑没什么改变，是什么情况_(:3 」∠ )_

### ISSUE THREAD

**Issue by alianrock** [barretlee/autoconfig-mac-vimrc#3]
macvim下的，整体还是白色的背景，而不是黑色的，也没有侧边栏文件栏，请问是什么情况_(:3 」∠ )_

**Comment by barretlee** [comment]
- 更换背景：`ESC,bg`
- 进入目录后，`ESC,ne` 打开侧边文件栏

你可以尝试着读一读 `~/.vimrc` 文件。
