### ISSUE TITLE
安装报如下错误

### ISSUE THREAD

**Issue by wangwanqiang** [barretlee/autoconfig-mac-vimrc#4]
～～～
AsyncCommand requires vim compiled with +clientserver (see :help +clientserver)
Press ENTER or type command to continue
～～～

以后每次运行 vim 都报这个插件相关错误

**Comment by barretlee** [comment]
https://github.com/barretlee/autoconfig-mac-vimrc/blob/master/.vimrc#L67
修改 ~/.vimrc，注释掉上面链接指示的那行。

**Comment by wangwanqiang** [comment]
好的，非常好用，谢谢
