### ISSUE TITLE
How to remove completely?

### ISSUE THREAD

**Issue by Kongsea** [barretlee/autoconfig-mac-vimrc#6]
I install the package according to your gits. However, I found my TensorFlow cannot run anymore after installing.
So could you please tell me how to remove the packages?
Thank you.

**Comment by barretlee** [comment]
I'm sorry to hear that, it should not affect the operation of other software, you can recover the vim config in this way:

``` bash
cp ~/.vimrc-bak ~/.vimrc
```

remove completely:

``` bash
cp ~/.vimrc-bak ~/.vimrc
rm ~/.vimrc-bak
rm -rf ~/.vim
```

**Comment by Kongsea** [comment]
So weird, after I remove zsh, and source the .bashrc, my TensorFlow can work now.
Thank you for your kindly reply, now I can get my Ubuntu back to the original status.
